version: '3.9'
services:
  app:
    build: .
    container_name: nodejs2021Q4-service
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    restart: always
  postgres:
    build: ./database

