version: '3.9'
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: nodejs2021Q4-postgres
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    networks:
      - app-network
  app:
    build: .
    container_name: nodejs2021Q4-service
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - ./LOG:/app/LOG
      - files:/app/uploaded-files
    restart: always
    networks:
      - app-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network
volumes:
  files:
  db:
    driver: local
networks:
  app-network:
    driver: bridge
